POST http://localhost:8080/api/v1/account/register
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "pa$$word"
}

###

POST http://localhost:8080/api/v1/account/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "pa$$word"
}

###

GET http://localhost:8080/api/v1/account/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTczMjAxOTAsImlhdCI6MTc1NzIzMzc5MCwiaXNzIjoic2VydmljZWh1Yl9hcGkiLCJzdWIiOjF9.Op8odQDr81A77_KfPbmHERK-hjf9rOH-FmApoBxR58Q

###

POST http://localhost:8080/api/v1/account/logout
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE3NTczMjAxOTAsImlhdCI6MTc1NzIzMzc5MCwiaXNzIjoic2VydmljZWh1Yl9hcGkiLCJzdWIiOjF9.Op8odQDr81A77_KfPbmHERK-hjf9rOH-FmApoBxR58Q

###

POST http://localhost:8080/api/v1/account/forgot-password
Content-Type: application/json

{
  "email": "user@example.com"
}